[package]
name = "pulsar"
version = "0.3.0"
edition = "2018"
authors = [
    "Colin Stearns <cstearns@developers.wyyerd.com>",
    "Kevin Stenerson <kstenerson@developers.wyyerd.com>"
]

license = "MIT/Apache-2.0"
readme = "./README.md"
repository = "https://github.com/wyyerd/pulsar-rs"
documentation = "https://docs.rs/pulsar"
description = "Rust API bindings for Apache Pulsar"
keywords = ["pulsar", "api"]
categories = ["api-bindings"]

[badges]
travis-ci = {repository = "wyyerd/pulsar-rs"}

[dependencies]
bytes = "0.5.0"
crc = "1.0.0"
futures = "0.3"
nom = "5.0.0"
prost = "0.6.0"
prost-derive = "0.6.0"
tokio = {version = "0.2", features = ["rt-threaded"]}
tokio-util = {version = "0.3", features = ["codec"] }
rand = "0.7"
chrono = "0.4.6"
futures-timer = "3.0"
log = "0.4.6"
trust-dns-resolver = "0.19"
url = "2.1"
regex = "1.1.7"
bit-vec = "0.6"
lz4 = { version = "1.23", optional = true }

[dev-dependencies]
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"

[build-dependencies]
prost-build = "0.6.0"

[features]
default = [ "compression" ]
compression = [ "lz4" ]
